In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import numpy as np
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', 100)

#Regression
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge,Lasso
from sklearn.linear_model import ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import ExtraTreeRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn.preprocessing import normalize,scale

import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
import requests
from csv import writer
import re
import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option('display.max_columns',100)

import warnings
warnings.filterwarnings("ignore")

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge,Lasso
from sklearn.linear_model import ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
gb=GradientBoostingRegressor()

from sklearn.tree import ExtraTreeRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error


from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
def algo_test(x,y):

        
        R=Ridge()
        Lass=Lasso()
        E=ElasticNet()
        GBR=GradientBoostingRegressor()
        XGBC=XGBRegressor()
        kn=KNeighborsRegressor()
        
        
        x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.1,random_state=13)
        
        algos=[R,Lass,E,GBR,XGBC,kn]
        algo_names=['Ridge','Lasso','ElasticNet','Gradient Boosting','XGradientBoosting','KNeighbors']
        
        r2Score = []
        rmse = []
        mae = []
        
        result=pd.DataFrame(columns=['R2_score','RMSE','MAE'],index=algo_names)
        
        
        for algo in algos:
            p=algo.fit(x_train,y_train).predict(x_test)
            r2Score.append(r2_score(y_test,p))
            rmse.append(mean_squared_error(y_test,p)**.5)
            mae.append(mean_absolute_error(y_test,p))
        
            
        result['R2_score']=r2Score 
        result.RMSE=rmse
        result.MAE=mae


        return result.sort_values('R2_score',ascending=False)

In [3]:
source1=requests.get("https://www.hepsiemlak.com/duzce-satilik").text
source2=requests.get("https://www.hepsiemlak.com/duzce-satilik?page=2").text
source3=requests.get('https://www.hepsiemlak.com/duzce-satilik?page=3').text
source4=requests.get('https://www.hepsiemlak.com/duzce-satilik?page=4').text
source5=requests.get('https://www.hepsiemlak.com/duzce-satilik?page=5').text
source6=requests.get('https://www.hepsiemlak.com/duzce-satilik?page=6').text
source7=requests.get('https://www.hepsiemlak.com/duzce-satilik?page=7').text
source8=requests.get('https://www.hepsiemlak.com/duzce-satilik?page=8').text
source9=requests.get('https://www.hepsiemlak.com/duzce-satilik?page=9').text
source10=requests.get('https://www.hepsiemlak.com/duzce-satilik?page=10').text
source=source1+source2+source3+source4+source5+source6+source7+source8+source9+source10

In [4]:
soup = BeautifulSoup(source,"html.parser")

In [5]:
soup.beautify

In [6]:
container = soup.findAll("ul",{"class":"list-items-container"})

In [7]:
fiyat=soup.findAll("span",{"class":"list-view-price"})
yas=soup.findAll("span",{"class":"celly buildingAge"})
kat=soup.findAll("span",{"class":"celly floortype"})
boyut=soup.findAll("span",{"class":"celly houseRoomCount"})
metre2=soup.findAll("span",{"class":"celly squareMeter list-view-size"})

In [8]:
f=[]
y=[]
k=[]
b=[]
m=[]

In [9]:
for span in yas:
    print(span.text)
    y.append(span.text)

Sıfır Bina
5 Yaşında
8 Yaşında
Sıfır Bina
2 Yaşında
2 Yaşında
1 Yaşında
6 Yaşında
8 Yaşında
Sıfır Bina
25 Yaşında
4 Yaşında
5 Yaşında
7 Yaşında
5 Yaşında
15 Yaşında
2 Yaşında
Sıfır Bina
Sıfır Bina
6 Yaşında
Sıfır Bina
4 Yaşında
6 Yaşında
6 Yaşında
Sıfır Bina
3 Yaşında
4 Yaşında
15 Yaşında
5 Yaşında
9 Yaşında
10 Yaşında
5 Yaşında
7 Yaşında
12 Yaşında
Sıfır Bina
4 Yaşında
5 Yaşında
3 Yaşında
26 Yaşında
6 Yaşında
7 Yaşında
Sıfır Bina
21 Yaşında
Sıfır Bina
Sıfır Bina
20 Yaşında
20 Yaşında
20 Yaşında
3 Yaşında
5 Yaşında
Sıfır Bina
7 Yaşında
19 Yaşında
10 Yaşında
1 Yaşında
25 Yaşında
15 Yaşında
20 Yaşında
5 Yaşında
1 Yaşında
20 Yaşında
15 Yaşında
1 Yaşında
Sıfır Bina
2 Yaşında
Sıfır Bina
6 Yaşında
Sıfır Bina
Sıfır Bina
5 Yaşında
3 Yaşında
Sıfır Bina
1 Yaşında
5 Yaşında
8 Yaşında
7 Yaşında
5 Yaşında
1 Yaşında
Sıfır Bina
5 Yaşında
3 Yaşında
7 Yaşında
4 Yaşında
25 Yaşında
3 Yaşında
4 Yaşında
4 Yaşında
2 Yaşında
3 Yaşında
15 Yaşında
27 Yaşında
Sıfır Bina
6 Yaşında
5 Yaşında
5 Yaşında
Sıfır Bina
9 Yaşında
7 Yaşında
4 Yaşında
17 Yaşında
22 Yaşında
4 Yaşında
6 Yaşında
Sıfır Bina
7 Yaşında
5 Yaşında
Sıfır Bina
Sıfır Bina
4 Yaşında
18 Yaşında
4 Yaşında
6 Yaşında
25 Yaşında
5 Yaşında
8 Yaşında
5 Yaşında
3 Yaşında
5 Yaşında
7 Yaşında
Sıfır Bina
3 Yaşında
8 Yaşında
35 Yaşında
16 Yaşında
17 Yaşında
Sıfır Bina
4 Yaşında
4 Yaşında
4 Yaşında
Sıfır Bina
12 Yaşında
13 Yaşında
15 Yaşında
Sıfır Bina
7 Yaşında
Sıfır Bina
6 Yaşında
Sıfır Bina
4 Yaşında
4 Yaşında
15 Yaşında
12 Yaşında
3 Yaşında
5 Yaşında
14 Yaşında
1 Yaşında
4 Yaşında
Sıfır Bina
2 Yaşında
4 Yaşında
Sıfır Bina
9 Yaşında
1 Yaşında
6 Yaşında
Sıfır Bina
2 Yaşında
21 Yaşında
9 Yaşında
Sıfır Bina
15 Yaşında
7 Yaşında
2 Yaşında
Sıfır Bina
18 Yaşında
3 Yaşında
6 Yaşında
2 Yaşında
Sıfır Bina
Sıfır Bina
6 Yaşında
Sıfır Bina
15 Yaşında
Sıfır Bina
20 Yaşında
10 Yaşında
7 Yaşında
7 Yaşında
4 Yaşında
16 Yaşında
15 Yaşında
4 Yaşında
3 Yaşında
2 Yaşında
25 Yaşında
10 Yaşında
15 Yaşında
18 Yaşında
6 Yaşında
2 Yaşında
9 Yaşında
Sıfır Bina
12 Yaşında
8 Yaşında
5 Yaşında
5 Yaşında
Sıfır Bina
6 Yaşında
Sıfır Bina
15 Yaşında
Sıfır Bina
2 Yaşında
Sıfır Bina
7 Yaşında
18 Yaşında
Sıfır Bina
17 Yaşında
6 Yaşında
3 Yaşında
5 Yaşında
Sıfır Bina
Sıfır Bina
25 Yaşında
5 Yaşında
7 Yaşında
2 Yaşında
11 Yaşında
5 Yaşında
12 Yaşında
21 Yaşında
1 Yaşında
25 Yaşında
15 Yaşında
Sıfır Bina
10 Yaşında
2 Yaşında
Sıfır Bina
Sıfır Bina
7 Yaşında
Sıfır Bina
16 Yaşında
11 Yaşında
3 Yaşında
11 Yaşında
14 Yaşında
Sıfır Bina

In [10]:
for span in metre2:
    print(span.text)
    m.append(span.text)

                          220 m2

                          135 m2

                          130 m2

                          119 m2

                          200 m2

                          210 m2

                          65 m2

                          155 m2

                          145 m2

                          65 m2

                          130 m2

                          190 m2

                          230 m2

                          120 m2

                          735 m2

                          110 m2

                          87 m2

                          255 m2

                          360 m2

                          135 m2

                          145 m2

                          80 m2

                          110 m2

                          135 m2

                          155 m2

                          135 m2

                          130 m2

                          138 m2

                          128 m2

                          240 m2

                          149 m2

                          95 m2

                          230 m2

                          190 m2

                          128 m2

                          85 m2

                          200 m2

                          130 m2

                          140 m2

                          90 m2

                          79 m2

                          270 m2

                          130 m2

                          135 m2

                          110 m2

                          145 m2

                          115 m2

                          120 m2

                          125 m2

                          95 m2

                          145 m2

                          130 m2

                          145 m2

                          420 m2

                          135 m2

                          300 m2

                          116 m2

                          110 m2

                          147 m2

                          159 m2

                          180 m2

                          118 m2

                          148 m2

                          160 m2

                          70 m2

                          130 m2

                          65 m2

                          93 m2

                          64 m2

                          135 m2

                          71 m2

                          157 m2

                          192 m2

                          65 m2

                          176 m2

                          110 m2

                          175 m2

                          135 m2

                          148 m2

                          160 m2

                          120 m2

                          147 m2

                          120 m2

                          115 m2

                          117 m2

                          166 m2

                          115 m2

                          200 m2

                          68 m2

                          120 m2

                          135 m2

                          132 m2

                          85 m2

                          130 m2

                          150 m2

                          220 m2

                          90 m2

                          125 m2

                          115 m2

                          100 m2

                          110 m2

                          50 m2

                          65 m2

                          200 m2

                          135 m2

                          65 m2

                          130 m2

                          135 m2

                          140 m2

                          130 m2

                          130 m2

                          55 m2

                          110 m2

                          95 m2

                          130 m2

                          140 m2

                          120 m2

                          110 m2

                          85 m2

                          140 m2

                          125 m2

                          125 m2

                          125 m2

                          135 m2

                          135 m2

                          125 m2

                          130 m2

                          125 m2

                          110 m2

                          90 m2

                          350 m2

                          380 m2

                          130 m2

                          200 m2

                          100 m2

                          98 m2

                          200 m2

                          178 m2

                          101 m2

                          98 m2

                          130 m2

                          126 m2

                          136 m2

                          110 m2

                          123 m2

                          65 m2

                          190 m2

                          75 m2

                          130 m2

                          120 m2

                          128 m2

                          135 m2

                          375 m2

                          250 m2

                          90 m2

                          110 m2

                          100 m2

                          350 m2

                          155 m2

                          220 m2

                          139 m2

                          140 m2

                          140 m2

                          110 m2

                          800 m2

                          125 m2

                          85 m2

                          60 m2

                          110 m2

                          150 m2

                          100 m2

                          170 m2

                          236 m2

                          270 m2

                          330 m2

                          90 m2

                          120 m2

                          70 m2

                          200 m2

                          320 m2

                          135 m2

                          60 m2

                          205 m2

                          105 m2

                          906 m2

                          140 m2

                          120 m2

                          98 m2

                          170 m2

                          175 m2

                          90 m2

                          310 m2

                          140 m2

                          140 m2

                          110 m2

                          124 m2

                          130 m2

                          218 m2

                          160 m2

                          250 m2

                          100 m2

                          500 m2

                          120 m2

                          125 m2

                          230 m2

                          150 m2

                          110 m2

                          60 m2

                          90 m2

                          260 m2

                          195 m2

                          130 m2

                          150 m2

                          100 m2

                          95 m2

                          252 m2

                          150 m2

                          210 m2

                          105 m2

                          100 m2

                          140 m2

                          320 m2

                          130 m2

                          135 m2

                          205 m2

                          359 m2

                          300 m2

                          120 m2

                          80 m2

                          140 m2

                          500 m2

                          70 m2

                          120 m2

                          900 m2

                          125 m2

In [11]:
for span in boyut:
    print(span.text)
    b.append(span.text)

4 + 1
3 + 1
2 + 1
3 + 1
5 + 1
3 + 1
1 + 1
3 + 1
3 + 1
2 + 1
3 + 1
3 + 1
4 + 1
3 + 1
5 + 2
2 + 1
2 + 1
4 + 1
5 + 1
2 + 1
3 + 1
2 + 0
2 + 1
3 + 1
3 + 1
3 + 1
3 + 1
3 + 1
3 + 1
4 + 1
3 + 1
2 + 1
5 + 1
3 + 1
3 + 1
2 + 1
4 + 1
3 + 1
3 + 1
2 + 1
1 + 1
4 + 1
3 + 1
3 + 1
3 + 1
3 + 1
3 + 1
3 + 1
2 + 1
2 + 1
3 + 1
3 + 1
3 + 1
5 + 2
3 + 1
3 + 3
3 + 1
3 + 1
3 + 1
3 + 1
4 + 1
3 + 1
3 + 1
3 + 1
1 + 1
3 + 1
1 + 1
2 + 1
1 + 1
3 + 1
1 + 1
3 + 1
4 + 1
1 + 1
8 + 2
2 + 1
4 + 1
2 + 1
3 + 1
3 + 1
3 + 1
3 + 1
3 + 1
6 + 2
3 + 1
3 + 1
3 + 1
5 + 1
1 + 1
3 + 1
3 + 1
3 + 102
2 + 1
3 + 1
3 + 1
5 + 2
2 + 1
3 + 1
3 + 1
2 + 1
2 + 1
1 + 1
1 + 1
4 + 1
3 + 1
1 + 1
3 + 1
3 + 1
3 + 1
3 + 1
3 + 1
1 + 1
4 + 2
2 + 1
3 + 1
3 + 1
3 + 1
2 + 1
2 + 1
3 + 1
2 + 1
3 + 1
2 + 1
3 + 1
3 + 1
2 + 1
3 + 1
2 + 1
3 + 1
2 + 1
3 + 2
6 + 2
3 + 1
4 + 1
2 + 1
2 + 1
4 + 2
2 + 1
2 + 1
2 + 1
3 + 1
3 + 1
3 + 1
2 + 1
3 + 1
1 + 1
3 + 1
2 + 1
3 + 1
3 + 1
3 + 1
3 + 1
5 + 2
5 + 2
2 + 1
2 + 1
2 + 1
5 + 1
3 + 1
4 + 1
3 + 1
3 + 1
3 + 1
3 + 1
8 + 2
3 + 1
2 + 1
2 + 1
2 + 1
3 + 1
2 + 1
3 + 1
4 + 1
5 + 3
5 + 1
2 + 1
3 + 1
2 + 1
4 + 2
5 + 1
3 + 1
1 + 1
3 + 1
2 + 1
3 + 1
3 + 1
3 + 1
2 + 1
3 + 2
3 + 1
2 + 1
4 + 1
3 + 1
3 + 1
2 + 1
2 + 1
3 + 1
4 + 1
3 + 1
4 + 1
2 + 1
5 + 2
2 + 1
3 + 1
4 + 1
4 + 1
2 + 1
2 + 0
2 + 1
4 + 1
3 + 1
3 + 1
3 + 1
2 + 1
2 + 1
5 + 2
3 + 1
4 + 1
2 + 1
2 + 1
3 + 1
8 + 2
3 + 1
3 + 1
3 + 1
4 + 1
5 + 1
3 + 1
2 + 1
3 + 1
4 + 1
1 + 1
10 + 2
10 + 3
3 + 1

In [12]:
for span in kat:
    print(span.text)
    k.append(span.text)

                      Bahçe Katı

                      Yüksek Giriş

                      4. Kat

                      Ara Kat



                      En Üst Kat

                      2. Kat

                      Bahçe Katı

                      En Üst Kat

                      En Üst Kat

                      5. Kat

                      2. Kat

                      En Üst Kat

                      4. Kat

                      Bahçe Katı

                      Yüksek Giriş

                      En Üst Kat





                      Yüksek Giriş

                      1. Kat

                      En Üst Kat

                      En Üst Kat

                      Zemin

                      Zemin

                      2. Kat

                      Yüksek Giriş

                      En Üst Kat

                      Yüksek Giriş

                      En Üst Kat

                      Zemin

                      Kot 1

                      En Üst Kat

                      2. Kat

                      6. Kat

                      3. Kat

                      2. Kat

                      En Üst Kat

                      Ara Kat

                      3. Kat

                      1. Kat



                      En Üst Kat

                      Ara Kat

                      Ara Kat

                      1. Kat

                      5. Kat

                      Giriş Katı

                      Ara Kat

                      Yüksek Giriş

                      Ara Kat

                      2. Kat

                      2. Kat



                      En Üst Kat



                      Ara Kat

                      Ara Kat

                      1. Kat

                      Ara Kat



                      Yüksek Giriş

                      2. Kat



                      Ara Kat

                      2. Kat

                      Ara Kat

                      2. Kat

                      En Üst Kat

                      3. Kat

                      2. Kat

                      3. Kat

                      1. Kat

                      Yüksek Giriş



                      Ara Kat

                      En Üst Kat

                      Giriş Katı

                      2. Kat

                      En Üst Kat

                      1. Kat

                      En Üst Kat

                      2. Kat



                      Giriş Katı

                      2. Kat

                      Ara Kat

                      En Üst Kat

                      En Üst Kat

                      Bahçe Katı

                      3. Kat

                      Ara Kat

                      Yüksek Giriş

                      Zemin

                      1. Kat



                      5. Kat

                      2. Kat

                      Yüksek Giriş

                      3. Kat

                      Ara Kat

                      5. Kat

                      Yüksek Giriş



                      Ara Kat

                      Yüksek Giriş

                      En Üst Kat

                      Yüksek Giriş

                      Giriş Katı

                      En Üst Kat

                      3. Kat

                      Ara Kat



                      2. Kat

                      1. Kat

                      En Üst Kat

                      5. Kat

                      Yüksek Giriş

                      Yüksek Giriş

                      En Üst Kat

                      Yüksek Giriş

                      Ara Kat

                      1. Kat

                      Giriş Katı

                      3. Kat

                      Ara Kat

                      5. Kat

                      Yüksek Giriş

                      En Üst Kat

                      Kot 1





                      Ara Kat



                      3. Kat

                      En Üst Kat

                      En Üst Kat

                      En Üst Kat

                      3. Kat

                      En Üst Kat

                      En Üst Kat

                      Ara Kat

                      2. Kat

                      2. Kat

                      3. Kat

                      4. Kat

                      2. Kat

                      En Üst Kat

                      4. Kat

                      2. Kat

                      En Üst Kat

                      Giriş Katı





                      Yüksek Giriş

                      Ara Kat

                      En Üst Kat

                      Ara Kat

                      Ara Kat



                      En Üst Kat

                      2. Kat

                      3. Kat

                      2. Kat



                      3. Kat

                      Ara Kat

                      5. Kat

                      4. Kat

                      1. Kat

                      Giriş Katı

                      En Üst Kat







                      Giriş Katı

                      Yüksek Giriş

                      Ara Kat





                      4. Kat

                      3. Kat

                      1. Kat

                      2. Kat



                      5. Kat

                      Villa Katı

                      3. Kat

                      En Üst Kat

                      Ara Kat

                      Ara Kat



                      1. Kat

                      Bahçe Katı

                      Yüksek Giriş

                      3. Kat

                      1. Kat

                      Bahçe Katı





                      8. Kat



                      Bahçe Katı

                      En Üst Kat



                      Ara Kat

                      Giriş Katı

                      Ara Kat

                      En Üst Kat



                      Kot 2



                      Bahçe Katı

                      Ara Kat

                      Yüksek Giriş

                      Villa Katı

                      Yüksek Giriş

                      En Üst Kat

                      3. Kat

                      4. Kat

                      5. Kat



                      Yüksek Giriş

                      Yüksek Giriş

                      5. Kat





                      2. Kat

                      1. Kat

                      Yüksek Giriş

                      Bahçe Katı

                      3. Kat





                      Kot 2

In [13]:
for span in fiyat:
    print(span.text)
    f.append(span.text)

              4.650.000
              TL

              798.000
              TL

              1.100.000
              TL

              1.150.000
              TL

              1.600.000
              TL

              1.450.000
              TL

              530.000
              TL

              1.296.000
              TL

              1.600.000
              TL

              860.000
              TL

              600.000
              TL

              2.600.000
              TL

              1.590.000
              TL

              1.270.000
              TL

              3.050.000
              TL

              800.000
              TL

              850.000
              TL

              2.625.000
              TL

              4.300.000
              TL

              735.000
              TL

              1.650.000
              TL

              630.000
              TL

              820.000
              TL

              1.025.000
              TL

              1.300.000
              TL

              999.000
              TL

              965.000
              TL

              850.000
              TL

              890.000
              TL

              1.570.000
              TL

              1.500.000
              TL

              558.000
              TL

              1.520.000
              TL

              1.690.000
              TL

              1.750.000
              TL

              800.000
              TL

              1.550.000
              TL

              1.079.000
              TL

              850.000
              TL

              480.000
              TL

              400.000
              TL

              2.550.000
              TL

              850.000
              TL

              1.100.000
              TL

              1.097.000
              TL

              565.000
              TL

              750.000
              TL

              795.000
              TL

              925.000
              TL

              630.000
              TL

              855.000
              TL

              1.250.000
              TL

              2.750.000
              TL

              2.950.000
              TL

              1.050.000
              TL

              1.200.000
              TL

              770.000
              TL

              780.000
              TL

              1.200.000
              TL

              2.650.000
              TL

              3.750.000
              TL

              650.000
              TL

              2.650.000
              TL

              1.350.000
              TL

              529.000
              TL

              1.050.000
              TL

              725.000
              TL

              750.000
              TL

              650.000
              TL

              1.320.000
              TL

              650.000
              TL

              1.175.000
              TL

              3.750.000
              TL

              475.000
              TL

              1.000.000
              TL

              875.000
              TL

              1.250.000
              TL

              770.000
              TL

              2.650.000
              TL

              1.149.000
              TL

              827.000
              TL

              1.280.000
              TL

              1.550.000
              TL

              1.500.000
              TL

              878.000
              TL

              1.750.000
              TL

              795.000
              TL

              2.000.000
              TL

              405.000
              TL

              750.000
              TL

              800.000
              TL

              900.000
              TL

              580.000
              TL

              749.000
              TL

              1.100.000
              TL

              2.500.000
              TL

              535.000
              TL

              1.300.000
              TL

              1.150.000
              TL

              1.350.000
              TL

              620.000
              TL

              460.000
              TL

              379.000
              TL

              2.550.000
              TL

              995.000
              TL

              385.000
              TL

              950.000
              TL

              630.000
              TL

              850.000
              TL

              650.000
              TL

              1.750.000
              TL

              420.000
              TL

              1.250.000
              TL

              565.000
              TL

              950.000
              TL

              1.340.000
              TL

              1.050.000
              TL

              650.000
              TL

              525.000
              TL

              1.200.000
              TL

              850.000
              TL

              825.000
              TL

              2.250.000
              TL

              850.000
              TL

              760.000
              TL

              1.350.000
              TL

              1.150.000
              TL

              850.000
              TL

              975.000
              TL

              575.000
              TL

              3.500.000
              TL

              3.150.000
              TL

              419.000
              TL

              2.090.000
              TL

              1.200.000
              TL

              525.000
              TL

              1.850.000
              TL

              2.500.000
              TL

              875.000
              TL

              775.000
              TL

              935.000
              TL

              900.000
              TL

              1.200.000
              TL

              800.000
              TL

              575.000
              TL

              780.000
              TL

              2.600.000
              TL

              690.000
              TL

              1.000.000
              TL

              620.000
              TL

              1.120.000
              TL

              650.000
              TL

              5.500.000
              TL

              4.150.000
              TL

              638.000
              TL

              670.000
              TL

              649.000
              TL

              1.950.000
              TL

              935.000
              TL

              3.550.000
              TL

              1.200.000
              TL

              1.200.000
              TL

              1.450.000
              TL

              625.000
              TL

              10.200.000
              TL

              1.350.000
              TL

              875.000
              TL

              500.000
              TL

              690.000
              TL

              1.050.000
              TL

              710.000
              TL

              1.050.000
              TL

              3.150
              TL

              2.350.000
              TL

              2.100.000
              TL

              719.000
              TL

              649.000
              TL

              550.000
              TL

              6.000.000
              TL

              3.000.000
              TL

              880.000
              TL

              625.000
              TL

              1.790.000
              TL

              925.000
              TL

              3.300.000
              TL

              1.100.000
              TL

              1.450.000
              TL

              850.000
              TL

              1.600.000
              TL

              1.990.000
              TL

              649.000
              TL

              2.100.000
              TL

              570.000
              TL

              1.400.000
              TL

              550.000
              TL

              2.146.000
              TL

              870.000
              TL

              2.950.000
              TL

              1.750.000
              TL

              2.700.000
              TL

              840.000
              TL

              5.500.000
              TL

              750.000
              TL

              1.450.000
              TL

              2.750.000
              TL

              850.000
              TL

              885.000
              TL

              440.000
              TL

              825.000
              TL

              4.000.000
              TL

              2.785.000
              TL

              1.600.000
              TL

              2.200.000
              TL

              790.000
              TL

              700.000
              TL

              1.800.000
              TL

              1.350.000
              TL

              1.685.000
              TL

              520.000
              TL

              1.200.000
              TL

              500.000
              TL

              2.550.000
              TL

              830.000
              TL

              1.079.000
              TL

              1.850.000
              TL

              5.951.000
              TL

              2.700.000
              TL

              910.000
              TL

              585.000
              TL

              1.750.000
              TL

              1.650.000
              TL

              385.000
              TL

              2.150.000
              TL

              3.250.000
              TL

              700.000
              TL

In [14]:
a = {'Yas':y,'Metre2':m,'Boyut':b,'Kat':k,'Fiyat':f}

In [15]:
df = pd.DataFrame.from_dict(a, orient='index')
df = df.transpose()
df

,Yas,Metre2,Boyut,Kat,Fiyat
0,Sıfır Bina,\n 220 m2,4 + 1,\n Bahçe Katı,\n 4.650.000\n TL
1,5 Yaşında,\n 135 m2,3 + 1,\n Yüksek Giriş,\n 798.000\n TL
2,8 Yaşında,\n 130 m2,2 + 1,\n 4. Kat,\n 1.100.000\n TL
3,Sıfır Bina,\n 119 m2,3 + 1,\n Ara Kat,\n 1.150.000\n TL
4,2 Yaşında,\n 200 m2,5 + 1,\n,\n 1.600.000\n TL
...,...,...,...,...,...
230,11 Yaşında,\n 500 m2,4 + 1,\n Bahçe Katı,\n 1.650.000\n TL
231,3 Yaşında,\n 70 m2,1 + 1,\n 3. Kat,\n 385.000\n TL
232,11 Yaşında,\n 120 m2,10 + 2,\n,\n 2.150.000\n TL
233,14 Yaşında,\n 900 m2,10 + 3,\n,\n 3.250.000\n TL
234,Sıfır Bina,\n 125 m2,3 + 1,\n Kot 2,\n 700.000\n TL

In [16]:
#df.to_excel("düzce.xlsx")

In [17]:
df = pd.read_excel("düzce.xlsx")
df.drop('Unnamed: 0', axis=1, inplace=True)
df = df.rename(columns = {'Yas': 'age',"Metre2":"area","Boyut":"dimension","Kat":"floor","Fiyat":"price"})
df

,age,area,dimension,floor,price
0,Sıfır Bina,\n 220 m2,4 + 1,\n Bahçe Katı,\n 4.650.000\n TL
1,5 Yaşında,\n 135 m2,3 + 1,\n Yüksek Giriş,\n 798.000\n TL
2,8 Yaşında,\n 130 m2,2 + 1,\n 4. Kat,\n 1.100.000\n TL
3,Sıfır Bina,\n 119 m2,3 + 1,\n Ara Kat,\n 1.150.000\n TL
4,2 Yaşında,\n 200 m2,5 + 1,7\n,\n 1.600.000\n TL
...,...,...,...,...,...
230,11 Yaşında,\n 500 m2,4 + 1,\n Bahçe Katı,\n 1.650.000\n TL
231,3 Yaşında,\n 70 m2,1 + 1,\n 3. Kat,\n 385.000\n TL
232,11 Yaşında,\n 120 m2,10 + 2,7\n,\n 2.150.000\n TL
233,14 Yaşında,\n 900 m2,10 + 3,7\n,\n 3.250.000\n TL
234,Sıfır Bina,\n 125 m2,3 + 1,\n Kot 2,\n 700.000\n TL

In [18]:
df.isnull().sum()

age          0
area         0
dimension    0
floor        0
price        0
dtype: int64

In [19]:
df['age'].value_counts()

Sıfır Bina    51
5 Yaşında     24
4 Yaşında     20
6 Yaşında     16
7 Yaşında     16
2 Yaşında     14
3 Yaşında     14
15 Yaşında    13
1 Yaşında      9
25 Yaşında     7
8 Yaşında      6
20 Yaşında     6
12 Yaşında     5
10 Yaşında     5
9 Yaşında      5
18 Yaşında     4
21 Yaşında     3
17 Yaşında     3
16 Yaşında     3
11 Yaşında     3
14 Yaşında     2
26 Yaşında     1
19 Yaşında     1
27 Yaşında     1
22 Yaşında     1
35 Yaşında     1
13 Yaşında     1
Name: age, dtype: int64

In [20]:
df['dimension'].value_counts()

3 + 1      110
2 + 1       56
4 + 1       22
1 + 1       15
5 + 1        8
5 + 2        7
8 + 2        3
4 + 2        3
2 + 0        2
6 + 2        2
3 + 2        2
3 + 3        1
3 + 102      1
5 + 3        1
10 + 2       1
10 + 3       1
Name: dimension, dtype: int64

In [21]:
df['price'].value_counts()

\n              850.000\n              TL      10
\n              1.200.000\n              TL     8
\n              650.000\n              TL       6
\n              1.050.000\n              TL     5
\n              1.750.000\n              TL     5
                                               ..
\n              1.149.000\n              TL     1
\n              475.000\n              TL       1
\n              1.175.000\n              TL     1
\n              1.320.000\n              TL     1
\n              3.250.000\n              TL     1
Name: price, Length: 140, dtype: int64

In [22]:
df["floor"] = df["floor"].str.replace("\n","")

In [23]:
df["floor"].unique()

array(['                      Bahçe Katı',
       '                      Yüksek Giriş',
       '                      4. Kat', '                      Ara Kat',
       '7', '                      En Üst Kat',
       '                      2. Kat', '                      5. Kat',
       '                      1. Kat', '                      Zemin',
       '                      Kot 1', '                      6. Kat',
       '                      3. Kat', '                      Giriş Katı',
       '                      Villa Katı', '                      8. Kat',
       '                      Kot 2'], dtype=object)

In [24]:
df['floor'].value_counts()

7                                     38
                      En Üst Kat      38
                      Ara Kat         31
                      Yüksek Giriş    25
                      2. Kat          24
                      3. Kat          18
                      1. Kat          14
                      5. Kat          10
                      Giriş Katı       9
                      Bahçe Katı       9
                      4. Kat           7
                      Zemin            4
                      Kot 1            2
                      Villa Katı       2
                      Kot 2            2
                      6. Kat           1
                      8. Kat           1
Name: floor, dtype: int64

In [25]:
df['area'].value_counts()

\n                          130 m2    19
\n                          135 m2    16
\n                          110 m2    15
\n                          120 m2    12
\n                          140 m2    11
                                      ..
\n                          166 m2     1
\n                          68 m2      1
\n                          132 m2     1
\n                          50 m2      1
\n                          900 m2     1
Name: area, Length: 85, dtype: int64

In [26]:
df["age"] = df["age"].str.replace(" Yaşında","").str.replace("Sıfır Bina","0")
df["price"] = df["price"].str.replace("TL","").str.replace(".","").str.replace("\n","")
df['floor'] = df['floor'].str.replace("En Üst Kat","10").str.replace("Ara Kat","7").str.replace("Yüksek Giriş","0").str.replace("1. Kat","1").str.replace("2. Kat","2").str.replace("3. Kat","3").str.replace("4. Kat","4").str.replace("5. Kat","5").str.replace("6. Kat","6").str.replace("8. Kat","8").str.replace("Bahçe Katı","0").str.replace("Giriş Katı","0").str.replace("Zemin","0").str.replace("Kot 1","1").str.replace("Kot 2","2").str.replace("Villa Katı","3")
df['area'] = df['area'].str.replace("m2","").str.replace("\n","")
df["dimension"] = df["dimension"].str.replace("+","").str.replace("  ","")
df["floor"] = df["floor"].str.replace(" ","")
df["floor"] = df["floor"].str.replace("\n","")

df["age"] = df["age"].astype(int)
df["price"] = df["price"].astype(int)
df['area'] = df['area'].astype(int)
df["dimension"] = df["dimension"].astype(int)
df["floor"] = df["floor"].astype(int)

In [27]:
df

     age  area  dimension  floor    price
0      0   220         41      0  4650000
1      5   135         31      0   798000
2      8   130         21      4  1100000
3      0   119         31      7  1150000
4      2   200         51      7  1600000
..   ...   ...        ...    ...      ...
230   11   500         41      0  1650000
231    3    70         11      3   385000
232   11   120        102      7  2150000
233   14   900        103      7  3250000
234    0   125         31      2   700000

[235 rows x 5 columns]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        235 non-null    int32
 1   area       235 non-null    int32
 2   dimension  235 non-null    int32
 3   floor      235 non-null    int32
 4   price      235 non-null    int32
dtypes: int32(5)
memory usage: 4.7 KB

## Regression

In [29]:
y=df["price"]

In [30]:
x=df.drop("price",axis=1)

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3,random_state=7)

In [32]:
gbr=GradientBoostingRegressor()

In [33]:
pred =gbr.fit(x_train,y_train)

In [34]:
algo_test(x,y)

                   R2_score           RMSE            MAE
XGradientBoosting  0.781798  490153.994395  319013.755208
Gradient Boosting  0.760099  513948.282599  359312.106823
Lasso              0.529972  719391.502169  402321.762425
Ridge              0.529971  719392.042316  402315.046189
ElasticNet         0.529882  719460.064857  401630.381999
KNeighbors         0.529874  719466.481730  468608.333333